### ISSUE TITLE
MW72 questions

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-devanagari#1]
# csl-orig digitization
```
<L>12216<pc>0172-c<k1>upAhf<k2>upAhf
{#upAhf#}¦ {%upā-hṛ (upa-ā-),%} cl. 1. P. A. {%-harati,%}
<div n="lb"/>{%-te, -hartum,%} to offer; to make, prepare.
<LEND>

<L>12217<pc>0172-c<k1>upAhAra<k2>upAhAra
{%Upāhāra (upa-āhº), as,%}¦ m. slight refreshment
<div n="lb"/>(consisting of fruits, sweetmeats, &c.).
<LEND>

<L>12218<pc>0172-c<k1>upAhfta<k2>upAhfta
{%Upā-hṛta, as, ā, am,%}¦ offered, prepared; seized.
<LEND>
```

# Current Devanagari version

```
<L>12216<pc>0172-c<k1>upAhf<k2>upAhf
{#उपाहृ#}¦ {%upā-hṛ (upa-ā-),%} cl. 1. P. A. {%-harati,%}
<div n="lb"/>{%-te, -hartum,%} to offer; to make, prepare.
<LEND>

<L>12217<pc>0172-c<k1>upAhAra<k2>upAhAra
{%Upāhāra (upa-āhº), as,%}¦ m. slight refreshment
<div n="lb"/>(consisting of fruits, sweetmeats, &c.).
<LEND>

<L>12218<pc>0172-c<k1>upAhfta<k2>upAhfta
{%Upā-hṛta, as, ā, am,%}¦ offered, prepared; seized.
<LEND>
```

**Comment by drdhaval2785** [comment]
Does @Andhrabharati want the current one or the following one?
```
<L>12216<pc>0172-c<k1>upAhf<k2>upAhf
{#उपाहृ#}¦ {%उपा-हृ (उप-आ-),%} cl. 1. P. A. {%-हरति,%}
<div n="lb"/>{%-ते, -हर्तुम्,%} to offer; to make, prepare.
<LEND>

<L>12217<pc>0172-c<k1>upAhAra<k2>upAhAra
{%उपाहार (उप-आह्º), अस्,%}¦ m. slight refreshment
<div n="lb"/>(consisting of fruits, sweetmeats, &c.).
<LEND>

<L>12218<pc>0172-c<k1>upAhfta<k2>upAhfta
{%उपा-हृत, अस्, आ, अम्,%}¦ offered, prepared; seized.
<LEND>
```

**Comment by drdhaval2785** [comment]
The only issue in the change is Upāhāra -> उपाहार -> upāhāra . 
See that IAST capitalization gets lost in the reverse journey from Devanagari to IAST.

If converting to Devanagari seems to be of utmost importance, then only such a lossy conversion be done.
What is your say, Andhrabharati?

**Comment by Andhrabharati** [comment]
I would like to have the texts as much close to the print style as possible.

So, in this case, it is the "current version", that is as per the print.

BTW, where is this "current version" present as of now?

**Comment by Andhrabharati** [comment]
And I would be likely to change ṛ to ṛi etc. to match with print; all such could later be changed back to Cologne adopted transliteration with a global find/replace operation.

This should not be a big issue to break heads over it.

**Comment by Andhrabharati** [comment]
BTW, seen that Benfey is (was ?) a respected name in those times and I was thinking of taking it up after finishing my AE proofing, before AP90 proofing.

**Comment by Andhrabharati** [comment]
MW has just picked up his "cognate data" from Benfey and Bopp, without putting any addl. effort.

Of course he had clearly acknowledged both these works.

**Comment by Andhrabharati** [comment]
> Does @Andhrabharati want the current one or the following one?
> 
> ```
> <L>12216<pc>0172-c<k1>upAhf<k2>upAhf
> {#उपाहृ#}¦ {%उपा-हृ (उप-आ-),%} cl. 1. P. A. {%-हरति,%}
> <div n="lb"/>{%-ते, -हर्तुम्,%} to offer; to make, prepare.
> <LEND>
> 
> <L>12217<pc>0172-c<k1>upAhAra<k2>upAhAra
> {%उपाहार (उप-आह्º), अस्,%}¦ m. slight refreshment
> <div n="lb"/>(consisting of fruits, sweetmeats, &c.).
> <LEND>
> 
> <L>12218<pc>0172-c<k1>upAhfta<k2>upAhfta
> {%उपा-हृत, अस्, आ, अम्,%}¦ offered, prepared; seized.
> <LEND>
> ```

BTW, I would not be touching the metalines (when left in slp1 encoding) and  if some HW happens to be corrected in my working, it would be Cologne team's headache to "identify" all such & appropriately change k1 & k2 fields.

**Comment by Andhrabharati** [comment]
just like to mention that @funderburkjim had converted even the metalines while giving me MW99 in IAST, and I did (or remarked) corrections in them whereever needed.

**Comment by drdhaval2785** [comment]
> Upāhāra -> उपाहार -> upāhāra

Similar issue occurs in SCH also.

**Comment by drdhaval2785** [comment]
>  I would not be touching the metalines (when left in slp1 encoding) 

I can convert the headwords into Devanagari if you are willing to correct them too.

**Comment by Andhrabharati** [comment]
understood the point; no need to give me any examples for such points.

**Comment by drdhaval2785** [comment]
I had noted it for my reference. Needs to be handled in SCH also.

**Comment by drdhaval2785** [comment]
> BTW, where is this "current version" present as of now?

https://github.com/sanskrit-lexicon/csl-devanagari/tree/main/v02

**Comment by Andhrabharati** [comment]
I guess correcting the HWs and making the alt. words and group words is the fundamental work to be done in any dictionary.

And guess no one can have a second opinion about this, am I right?

**Comment by Andhrabharati** [comment]
> > BTW, where is this "current version" present as of now?
> 
> https://github.com/sanskrit-lexicon/csl-devanagari/tree/main/v02

so this is THE work done (or made public) NOW, as it is not in my cloned data.

**Comment by drdhaval2785** [comment]
> am I right?

Yes.

**Comment by drdhaval2785** [comment]
> so this is THE work done (or made public) NOW, as it is not in my cloned data.

Yes. It is currently ongoing.
11 dictionaries pending to be converted to the Devanagari data.

**Comment by Andhrabharati** [comment]
I have finished AP90 and PWG.

But, let's have all 38 works (CDSL home page is still having it as 37, even after adding ARMH!!) converted to Unicode in this repo, without any encodings.

Or leaving the two private works (AP57 and PD), 36 works.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-homepage/commit/78c7d1aba32a49eaad7d5137e58a1f2e2375ec53 has made the necessary change to show 38. It will show effect once Jim accesses Cologne servers and git pulls there.

**Comment by drdhaval2785** [comment]
All 36 dictionaries (except 2 private works) have been put in this repository.
If you feel like converting transliteration of any tag before you want to work on any work, please raise an issue here. Will make necessary changes to make your work easier and faster to the best of my abilities.

**Comment by Andhrabharati** [comment]
good to see this happen at last.

wonder why Jim did not do this small work (just two hours), in spite of my multiple requests.

could it be that he was doubting my intentions (I could anyway get the conversion done at my end if I want to), or my capabilities?

**Comment by gasyoun** [comment]
> See that IAST capitalization gets lost in the reverse journey from Devanagari to IAST.

There is an SLP1 solution for that. But not from Devanagari to IAST.

> BTW, seen that Benfey is (was ?) a respected name in those times and I was thinking of taking it up after finishing my AE proofing, before AP90 proofing.

No, Benfey never was a big name in dictionaries. So I would doubt him being so high in the priority list.

> MW has just picked up his "cognate data" from Benfey and Bopp, without putting any addl. effort.

Yes, mostly Bopp, so it's 200 years old - the cognates, around 1000 of them.

> wonder why Jim did not do this small work (just two hours), in spite of my multiple requests.

Whenever you wonder I wonder why you wonder - he's can't be too elastic - he is the shoulders on which we stand.

**Comment by Andhrabharati** [comment]
> 
> 
> [sanskrit-lexicon/csl-homepage@78c7d1a](https://github.com/sanskrit-lexicon/csl-homepage/commit/78c7d1aba32a49eaad7d5137e58a1f2e2375ec53) has made the necessary change to show 38. It will show effect once Jim accesses Cologne servers and git pulls there.

BTW, there are two works posterior to 1976 (PGN : 1978 and MCI : 1993), and the home page is still having the " (1832 till 1976)".

**Also request to change AP90 year back to 1890 from 1920; it is antecedent to many works here and having it dated thus (1920) puts it down below them all.**

**Comment by Andhrabharati** [comment]
> > MW has just picked up his "cognate data" from Benfey and Bopp, without putting any addl. effort.
> 
> Yes, mostly Bopp, so it's 200 years old - the cognates, around 1000 of them.

![image](https://user-images.githubusercontent.com/75209130/131918123-88b9e3e0-2983-4d03-b6a1-8c870f83c70f.png)

**Comment by gasyoun** [comment]
> there are two works posterior to 1976

Everything he notices @drdhaval2785 `(1832 till 1976)` -> `(1832 till 1993)`

**Comment by drdhaval2785** [comment]
Corrections made in the above commit to change 1976 to 1993.
Good to have someone who looks at everything de novo.

**Comment by drdhaval2785** [comment]
MW72 has data as sought for by Andhrabharati. 
Necessary changes in csl-homepage is also made. 
Nothing further remains to be done.
Closing.
