### ISSUE TITLE
BUR diff

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-devanagari#11]
typical diffs
```
9c9
< {%akāra|%}
---
> {%akāra.%}
18,19c18,19
< on écrit {%an: anārya|%} <ab>Gr.</ab>
< <lang n="greek"></lang>; <ab>lat.</ab> {%in;%} <ab>germ.</ab> {%un|%}
---
```

**Comment by drdhaval2785** [comment]
Keeping items in `{%...%}` tags as they are.

**Comment by drdhaval2785** [comment]
```
	Line 21141:	[{%ś, ṣ, s, h, s,%} {??} devant {%k,%} {??} devant {%p,%} et l'<s1 slp1="anusvAra">anusvāra</s1>
		[{%ś, ṣ, s, h, s,%} ᳲ devant {%k,%} ᳲ devant {%p,%} et l'<s1 slp1="anusvAra">anusvāra</s1>
		%% The ᳲ character is ardhavisarga, u+1CF2
```

I am not sure whether the items should be jihvAmUlIya and upadhmAnIya respectively before k and p?
@Andhrabharati

**Comment by drdhaval2785** [comment]
```
	Line 40679:	{%t,%} à {??} et même à {%s.%} L'articulation palatale de {#च#}
		{%t,%} à φ et même à {%s.%} L'articulation palatale de {#च#}
		%% This φ character is Greek small phi, u+03C6
		%% This entry shows that quite many Greek letters are mistakenly treated/marked as Sanskrit!! Needs a through checking throughout the text for such errors.
```

**Comment by Andhrabharati** [comment]
> ```
> 	Line 21141:	[{%ś, ṣ, s, h, s,%} {??} devant {%k,%} {??} devant {%p,%} et l'<s1 slp1="anusvAra">anusvāra</s1>
> 		[{%ś, ṣ, s, h, s,%} ᳲ devant {%k,%} ᳲ devant {%p,%} et l'<s1 slp1="anusvAra">anusvāra</s1>
> 		%% The ᳲ character is ardhavisarga, u+1CF2
> ```
> 
> I am not sure whether the items should be jihvAmUlIya and upadhmAnIya respectively before k and p?
> @Andhrabharati

ideally they should be different as you said; but having seen cologne works having it indifferently in all the works, I mentioned just one character.

I recall mentioning this diffrent marking to @funderburkjim in one of my recent posts (but as usual, he has skipped it!!), probably in PWG.
