### ISSUE TITLE
SCH diff

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-devanagari#18]
just like BEN
typical diffs are as follow.
```
24c24
< {#aMSaprAsa#} {%aṃśaprāsá%}¦  m. {%aṃśa%}'s Wurf , Maitr. S. 1 , 6 , 12 (105 , 1). {part=,seq=6,type=,n=2}
---
> {#aMSaprAsa#} {%aṃśaprāsá%}¦  m. {%Aṃśa%}'s Wurf , Maitr. S. 1 , 6 , 12 (105 , 1). {part=,seq=6,type=,n=2}
51c51
< {#aMSumadBedasaMgraha#} {%aṃśumadbhedasaṃgraha%}¦  m. Titel eines Werkes , Opp. Cat. 1. {part=,seq=15,type=,n=2}
---
> {#aMSumadBedasaMgraha#} {%Aṃśumadbhedasaṃgraha%}¦  m. Titel eines Werkes , Opp. Cat. 1. {part=,seq=15,type=,n=2}
```

**Comment by gasyoun** [comment]
> typical diffs are as follow.

And what do we learn from them?

**Comment by drdhaval2785** [comment]
We learn that I erroneously converted `{%...%}` cases to Devanagari. Whenever there was capitalization in IAST, it got lost while going IAST->Devanagari->IAST route.

**Comment by gasyoun** [comment]
> Whenever there was capitalization in IAST, it got lost while going IAST->Devanagari->IAST route.

Got it. That means devanagari can never be used for future conversions, only as a final output.

**Comment by Andhrabharati** [comment]
It is one of the reasons for my listing the works with IAST (extended with Initial cap.s; one may note that IAST has no provision originally or even as the standardised form-- it's just the influence of Romanisation by the Western world to introduce this feature and MW mentiones it in his intro pages clearly).

@drdhaval2785-- this is the answer for your query "what to do (with the list)" in another thread in this repo.

**Comment by drdhaval2785** [comment]
I still do not get what is meant by categories in #25

**Comment by Andhrabharati** [comment]
that's just the grouping as seen at csl-home page, nothing important other than some convenience (if any).

it is the book name that matters at the end.

**Comment by drdhaval2785** [comment]
Fine.
