### ISSUE TITLE
Devanagari in other than {#...#} tagging

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/csl-devanagari#24]
**§1. As per the "convention", the Devanagari text cannot be enclosed in {@...@} tags; it should only be within {#...#}.**

Searching for: {@[ऀ-ॿ]
gra.txt: 10016
md.txt: 7400

Searching for: {@-[ऀ-ॿ]
md.txt: 23428
`---------------------`

**§2. As per the "convention", the Devanagari text cannot be enclosed in {%...%} tags; it should only be within {#...#}.**

Searching for: {%-[ऀ-ॿ]
sch.txt: 65
stc.txt: 10943

Searching for: {%[ऀ-ॿ]
gra.txt: 41
md.txt: 1252
sch.txt: 38189
shs.txt: 10
stc.txt: 10933
wil.txt: 10762
yat.txt: 56189

**Comment by drdhaval2785** [comment]
pull the data.
All files regenerated.

**Comment by gasyoun** [comment]
@Andhrabharati happy?

**Comment by funderburkjim** [comment]
> §1. As per the "convention", the Devanagari text cannot be enclosed in {@...@} tags; it should only be within {#...#}.

In some cases,  there can be `{@{#X#}@}`, and possibly the other way around.

This occurs n ap57:  Example `{@{#-aH#}@}`    I don't know whether this 'double markup' occurs in any other 
dictionaries.

I don't know what the search `{@-[ऀ-ॿ]`  means, and why there are 10016 of them in gra.txt.
In gra.txt,  the {@X@} examples should have X as IAST, not SLP1.

Maybe my brief observations in this comment are off the mark, as the issue has been marked Closed.

**Comment by drdhaval2785** [comment]
There are not many diffs remaining. so, yes, this issue is closed. If anything surfaces again, it will be tracked in a separate issue.

**Comment by drdhaval2785** [comment]
There is no diff at all as on 03 October 2021.
