### ISSUE TITLE
Small changes in correction file

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-devanagari#30]
https://github.com/sanskrit-lexicon/csl-devanagari/commit/e173d658446b2240a80d48af6cc2e23590b10ec4

@Andhrabharati 
Just to draw your attention that I had to adjust these two items in your file to make it uniform. 
One used space instead of tab and one missed line number.

That caused the program to throw errors.

Necessary changes were made. 
Nothing requires to be done.

**Comment by drdhaval2785** [comment]
There was one more case, but I forgot to note it.

**Comment by Andhrabharati** [comment]
**I will try to see that such errors do not arise again.**

But as it is all manual work, sometimes they do creep-in and skip the eyes.

As you're handling them through scripts, they would be identified quickly & it is not too big a work (though at times could be irritating), isn't it?

**Comment by drdhaval2785** [comment]
I am not concerned about errors which scripts throw. I am concerned, lest some correction be skipped because of such an error. 

If my script is lenient in some way, there would be no error log and I may miss installing a valuable correction.
