### ISSUE TITLE
 PE non-Skt entries

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/csl-devanagari#36]
https://github.com/sanskrit-lexicon/csl-corrections/issues/69#issuecomment-993558238

The above context made me have a quick-look at the PE HWs; and found that quite many of them are not of Sanskrit, but are of Malayalam.

And few are from English and Tamil, which defy the slp1 notation-
`<L>560<pc>067-a<k1>अशूर्बनिपल्<k2>अशूर्बनिपल्	English`
`<L>1366<pc>165-b<k1>बुद्धिस्म्<k2>बुद्धिस्म्	English`
`<L>2437<pc>292-a<k1>गिल्गमीष्<k2>गिल्गमीष्	English`
`<L>2513<pc>300-a<k1>ग्रेएक्<k2>ग्रेएक्	English`
`<L>2680<pc>313-b<k1>हिप्पोच्रैतुस्<k2>हिप्पोच्रैतुस्	English`
`<L>2743<pc>318-a<k1>इन्दिअ<k2>इन्दिअ	English`
`<L>6552<pc>714-b<k1>शेक्किष्हार्<k2>शेक्किष्हार्	TamiL (could be rendered as शेक्किळार्)`

Also found some typos and printos-
`<L>1359<pc>165-a<k1>उध<k2>उध<h>II	Typo: बुध`
`<L>1771<pc>203-b<k1>दाश्राज्ञ<k2>दाश्राज्ञ	Typo: दाशराज्ञ`
`<L>2673<pc>312-b<k1>हिदिम्बवधपर्व<k2>हिदिम्बवधपर्व	Typo: हिडिम्बवधपर्व`
`<L>2674<pc>312-b<k1>हिदिम्बवन<k2>हिदिम्बवन	Typo: हिडिम्बवन`
`<L>2675<pc>312-b<k1>हिदिम्बी<k2>हिदिम्बी	Typo: हिडिम्बी`
`<L>3217<pc>383-b<k1>क<k2>क	Typo: कणाद`
`<L>5066<pc>575-a<k1>अर्णशाला<k2>अर्णशाला	Typo: पर्णशाला`
`<L>5288<pc>600-a<k1>रलम्ब<k2>रलम्ब<h>I	Typo: प्रलम्ब`
`<L>5949<pc>667-a<k1>शाइवाल<k2>शाइवाल	Printo: शैवाल`
`<L>6114<pc>681-b<k1>सम्वर्तवापी<k2>सम्वर्तवापी	Typo: संवर्तवापी`
`<L>6117<pc>681-b<k1>सम्वृत्ति<k2>सम्वृत्ति	Typo: संवृत्ति`
`<L>6929<pc>752-b<k1>सुदास्<k2>सुदास्<h>II	Printo: सुदास`

**Comment by gasyoun** [comment]
> not of Sanskrit, but are of Malayalam

How did you find them?

**Comment by Andhrabharati** [comment]
It is 'Andhrabharati' that did the task!

**Comment by gasyoun** [comment]
> It is 'Andhrabharati' that did the task!

How big is @Andhrabharati ? Do you know him?

**Comment by Andhrabharati** [comment]
> Do you know him?

It's me, did you forget?

> How big is @Andhrabharati ?

I had answered to this in the initial days itself!! Pl. recall the same.

**Comment by Andhrabharati** [comment]
@drdhaval2785 / @funderburkjim ,

This small issue could be closed in no time, if someone attends to it.

**Comment by funderburkjim** [comment]
## first group (English/Tamil)
added info markup. This does not affect the displays.
```
<L>1366<pc>165-b<k1>budDism<k2>budDism
BUDDHISM¦. <info n="English word"/> (BUDDHA-MATA). 
```
## second group
* Made the corrections at csl-orig,
* added two 'printo' items to csl-corrections  (pe_printchange.txt)

@drdhaval2785  
pulled csl-orig at Cologne.
Three dictionaries showed change: bop, mw, pe.
Updated Cologne displays for all three.

pulled csl-corrections

**Comment by funderburkjim** [comment]
@Andhrabharati   omission at [commit 2a06afb](https://github.com/sanskrit-lexicon/csl-orig/commit/2a06afb3ad6d1aca2066806e3da0349f9722aee2) corrected.
