### ISSUE TITLE
BOP study-1

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/csl-devanagari#39]
Remnants of LN forms:
- ī1 (2 cases) to be ì
- ē4 (112 cases) to be ế
- Ē0 (2 cases) to be Ê

@drdhaval2785, like to correct these?

**Comment by drdhaval2785** [comment]
Will do

**Comment by Andhrabharati** [comment]
If @funderburkjim is going to look at the BEN greek text anytime sooner, he might consider doing this correction also (as Dhaval seems occupied with some other activity).
